# Generated by Django 4.2.3 on 2024-11-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='searchBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=50)),
                ('from_source', models.CharField(max_length=50)),
                ('to_desti', models.CharField(max_length=50)),
                ('via_city', models.CharField(max_length=50, null=True)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('bus_ac', models.BooleanField()),
                ('bus_nonac', models.BooleanField()),
                ('bus_ac_check_text', models.CharField(max_length=10, null=True)),
                ('bus_sleeper_seater_text', models.CharField(max_length=10, null=True)),
                ('bus_price', models.IntegerField()),
                ('bus_seat', models.IntegerField()),
                ('bus_occupy_seat', models.IntegerField()),
                ('seater', models.BooleanField()),
                ('sleeper', models.BooleanField()),
                ('booked_seat_numbers', models.TextField(blank=True, default='')),
            ],
        ),
    ]
