# Generated by Django 4.2.3 on 2024-11-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueBus', '0002_alter_searchbus_bus_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchbus',
            name='bus_price',
            field=models.IntegerField(),
        ),
    ]
